--- #YAML:1.0
name:                POE-Component-Pool-DBI
version:             0.014
abstract:            A POE Component for managing Boss/Worker DBI pools
license:             ~
author:              
    - Scott S. McCoy (tag@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POE:                           0.3
    POE::Component::Pool::Thread:  0.015
    threads:                       1.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
